### ISSUE TITLE
Can you upload how to use your plugin on youtube?

### ISSUE THREAD

**Issue by mattun** [RLoris/JsonXmlHelperDoc#1]
Hi
I bought your plugin, But I can't understand how to use it.
I am not professional in blueprint, but I always write programming.

Thanks

**Comment by RLoris** [comment]
Hi @mattun,

How can I help you, what are you trying to achieve ?
Can you show me the JSON or XML you want to create/get ?

**Comment by RLoris** [comment]
I will not make a youtube video but I will improve the documentation if it's not clear enough !
Can you tell me what you do not understand or need help with ?

**Comment by RLoris** [comment]
@mattun I don't have any news from you thus I'm closing this issue ! You can still reopen an issue if you want my help...
