### ISSUE TITLE
Feature request, add compatibility with UE 5.5

### ISSUE THREAD

**Issue by Axagthoth** [RLoris/JsonXmlHelperDoc#3]
Hi RLoris! First of all I wanted to thank you for your excellent plugins. I use both the Serialization Helper and the Web Communication Helper, and they're both a charm to work with. I know this is probably the wrong channel to ask for this, but with all the Fab migration I can't find any feature request section in the marketplace anymore.

As the title suggests, this is to ask if there's any chance you might update your plugins to work with UE v5.5? I'm really pushing to migrate our current project to this version because of the improvements to DMX and the addition of the "native" NDI plugin, but I'm missing your plugins in the mix (and they've become quite essential). 

Thanks a lot!

**Comment by RLoris** [comment]
Hey there,

Thanks for using my plugins and your kind words !

All my plugins will be updated to support 5.5. I will need to test and update them during my free time on weekends.

Once the update is submitted and approved by Epic, you will be able to retrieve them directly from fab.

Stay tuned

**Comment by Axagthoth** [comment]
Ahh, that's excellent news! Thanks a lot, we'll be eagerly awaiting the release.

**Comment by RLoris** [comment]
Hey there, fyi, all my plugins now support 5.5 and can be retrieved from fab !
